---
- name: Converge - Run remediate role on mock IOS device
  hosts: all
  gather_facts: false
  roles:
    - role: network.compliance.remediate
      vars:
        compliance:
          framework: stig
          platform: ios
        compliance_remediate:
          cat1: true
          cat2: true
          cat3: true
